-- Starter exercise library (built-in entries: user_id null, is_custom false).
-- Generated from free-exercise-db (https://github.com/yuhonas/free-exercise-db),
-- 876 entries deduplicated case-insensitively to match the
-- exercises_builtin_name_key index in 0002.

insert into exercises (name, muscle_group, equipment) values
  ('3/4 Sit-Up', 'abdominals', 'body only'),
  ('90/90 Hamstring', 'hamstrings', 'body only'),
  ('Ab Crunch Machine', 'abdominals', 'machine'),
  ('Ab Roller', 'abdominals', 'other'),
  ('Adductor', 'adductors', 'foam roll'),
  ('Adductor/Groin', 'adductors', null),
  ('Advanced Kettlebell Windmill', 'abdominals', 'kettlebells'),
  ('Air Bike', 'abdominals', 'body only'),
  ('All Fours Quad Stretch', 'quadriceps', 'body only'),
  ('Alternate Hammer Curl', 'biceps', 'dumbbell'),
  ('Alternate Heel Touchers', 'abdominals', 'body only'),
  ('Alternate Incline Dumbbell Curl', 'biceps', 'dumbbell'),
  ('Alternate Leg Diagonal Bound', 'quadriceps', null),
  ('Alternating Cable Shoulder Press', 'shoulders', 'cable'),
  ('Alternating Deltoid Raise', 'shoulders', 'dumbbell'),
  ('Alternating Floor Press', 'chest', 'kettlebells'),
  ('Alternating Hang Clean', 'hamstrings', 'kettlebells'),
  ('Alternating Kettlebell Press', 'shoulders', 'kettlebells'),
  ('Alternating Kettlebell Row', 'middle back', 'kettlebells'),
  ('Alternating Renegade Row', 'middle back', 'kettlebells'),
  ('Ankle Circles', 'calves', null),
  ('Ankle On The Knee', 'glutes', null),
  ('Anterior Tibialis-SMR', 'calves', 'other'),
  ('Anti-Gravity Press', 'shoulders', 'barbell'),
  ('Arm Circles', 'shoulders', null),
  ('Arnold Dumbbell Press', 'shoulders', 'dumbbell'),
  ('Around The Worlds', 'chest', 'dumbbell'),
  ('Atlas Stone Trainer', 'lower back', 'other'),
  ('Atlas Stones', 'lower back', 'other'),
  ('Axle Deadlift', 'lower back', 'other'),
  ('Back Flyes - With Bands', 'shoulders', 'bands'),
  ('Backward Drag', 'quadriceps', 'other'),
  ('Backward Medicine Ball Throw', 'shoulders', 'medicine ball'),
  ('Balance Board', 'calves', 'other'),
  ('Ball Leg Curl', 'hamstrings', 'exercise ball'),
  ('Band Assisted Pull-Up', 'lats', 'other'),
  ('Band Good Morning', 'hamstrings', 'bands'),
  ('Band Good Morning (Pull Through)', 'hamstrings', 'bands'),
  ('Band Hip Adductions', 'adductors', 'bands'),
  ('Band Pull Apart', 'shoulders', 'bands'),
  ('Band Skull Crusher', 'triceps', 'bands'),
  ('Barbell Ab Rollout', 'abdominals', 'barbell'),
  ('Barbell Ab Rollout - On Knees', 'abdominals', 'barbell'),
  ('Barbell Bench Press - Medium Grip', 'chest', 'barbell'),
  ('Barbell Curl', 'biceps', 'barbell'),
  ('Barbell Curls Lying Against An Incline', 'biceps', 'barbell'),
  ('Barbell Deadlift', 'lower back', 'barbell'),
  ('Barbell Full Squat', 'quadriceps', 'barbell'),
  ('Barbell Glute Bridge', 'glutes', 'barbell'),
  ('Barbell Guillotine Bench Press', 'chest', 'barbell'),
  ('Barbell Hack Squat', 'quadriceps', 'barbell'),
  ('Barbell Hip Thrust', 'glutes', 'barbell'),
  ('Barbell Incline Bench Press - Medium Grip', 'chest', 'barbell'),
  ('Barbell Incline Shoulder Raise', 'shoulders', 'barbell'),
  ('Barbell Lunge', 'quadriceps', 'barbell'),
  ('Barbell Rear Delt Row', 'shoulders', 'barbell'),
  ('Barbell Rollout from Bench', 'abdominals', 'barbell'),
  ('Barbell Seated Calf Raise', 'calves', 'barbell'),
  ('Barbell Shoulder Press', 'shoulders', 'barbell'),
  ('Barbell Shrug', 'traps', 'barbell'),
  ('Barbell Shrug Behind The Back', 'traps', 'barbell'),
  ('Barbell Side Bend', 'abdominals', 'barbell'),
  ('Barbell Side Split Squat', 'quadriceps', 'barbell'),
  ('Barbell Squat', 'quadriceps', 'barbell'),
  ('Barbell Squat To A Bench', 'quadriceps', 'barbell'),
  ('Barbell Step Ups', 'quadriceps', 'barbell'),
  ('Barbell Walking Lunge', 'quadriceps', 'barbell'),
  ('Battling Ropes', 'shoulders', 'other'),
  ('Bear Crawl Sled Drags', 'quadriceps', 'other'),
  ('Behind Head Chest Stretch', 'chest', 'other'),
  ('Bench Dips', 'triceps', 'body only'),
  ('Bench Jump', 'quadriceps', 'body only'),
  ('Bench Press - Powerlifting', 'triceps', 'barbell'),
  ('Bench Press - With Bands', 'chest', 'bands'),
  ('Bench Press with Chains', 'triceps', 'barbell'),
  ('Bench Sprint', 'quadriceps', 'other'),
  ('Bent-Arm Barbell Pullover', 'lats', 'barbell'),
  ('Bent-Arm Dumbbell Pullover', 'chest', 'dumbbell'),
  ('Bent-Knee Hip Raise', 'abdominals', 'body only'),
  ('Bent Over Barbell Row', 'middle back', 'barbell'),
  ('Bent Over Dumbbell Rear Delt Raise With Head On Bench', 'shoulders', 'dumbbell'),
  ('Bent Over Low-Pulley Side Lateral', 'shoulders', 'cable'),
  ('Bent Over One-Arm Long Bar Row', 'middle back', 'barbell'),
  ('Bent Over Two-Arm Long Bar Row', 'middle back', 'barbell'),
  ('Bent Over Two-Dumbbell Row', 'middle back', 'dumbbell'),
  ('Bent Over Two-Dumbbell Row With Palms In', 'middle back', 'dumbbell'),
  ('Bent Press', 'abdominals', 'kettlebells'),
  ('Bicycling', 'quadriceps', 'other'),
  ('Bicycling, Stationary', 'quadriceps', 'machine'),
  ('Board Press', 'triceps', 'barbell'),
  ('Body-Up', 'triceps', 'body only'),
  ('Body Tricep Press', 'triceps', 'body only'),
  ('Bodyweight Flyes', 'chest', 'e-z curl bar'),
  ('Bodyweight Mid Row', 'middle back', 'other'),
  ('Bodyweight Squat', 'quadriceps', 'body only'),
  ('Bodyweight Walking Lunge', 'quadriceps', null),
  ('Bosu Ball Cable Crunch With Side Bends', 'abdominals', 'cable'),
  ('Bottoms-Up Clean From The Hang Position', 'forearms', 'kettlebells'),
  ('Bottoms Up', 'abdominals', 'body only'),
  ('Box Jump (Multiple Response)', 'hamstrings', 'other'),
  ('Box Skip', 'hamstrings', 'other'),
  ('Box Squat', 'quadriceps', 'barbell'),
  ('Box Squat with Bands', 'quadriceps', 'barbell'),
  ('Box Squat with Chains', 'quadriceps', 'barbell'),
  ('Brachialis-SMR', 'biceps', 'foam roll'),
  ('Bradford/Rocky Presses', 'shoulders', 'barbell'),
  ('Butt-Ups', 'abdominals', 'body only'),
  ('Butt Lift (Bridge)', 'glutes', 'body only'),
  ('Butterfly', 'chest', 'machine'),
  ('Cable Chest Press', 'chest', 'cable'),
  ('Cable Crossover', 'chest', 'cable'),
  ('Cable Crunch', 'abdominals', 'cable'),
  ('Cable Deadlifts', 'quadriceps', 'cable'),
  ('Cable Hammer Curls - Rope Attachment', 'biceps', 'cable'),
  ('Cable Hip Adduction', 'quadriceps', 'cable'),
  ('Cable Incline Pushdown', 'lats', 'cable'),
  ('Cable Incline Triceps Extension', 'triceps', 'cable'),
  ('Cable Internal Rotation', 'shoulders', 'cable'),
  ('Cable Iron Cross', 'chest', 'cable'),
  ('Cable Judo Flip', 'abdominals', 'cable'),
  ('Cable Lying Triceps Extension', 'triceps', 'cable'),
  ('Cable One Arm Tricep Extension', 'triceps', 'cable'),
  ('Cable Preacher Curl', 'biceps', 'cable'),
  ('Cable Rear Delt Fly', 'shoulders', 'cable'),
  ('Cable Reverse Crunch', 'abdominals', 'cable'),
  ('Cable Rope Overhead Triceps Extension', 'triceps', 'cable'),
  ('Cable Rope Rear-Delt Rows', 'shoulders', 'cable'),
  ('Cable Russian Twists', 'abdominals', 'cable'),
  ('Cable Seated Crunch', 'abdominals', 'cable'),
  ('Cable Seated Lateral Raise', 'shoulders', 'cable'),
  ('Cable Shoulder Press', 'shoulders', 'cable'),
  ('Cable Shrugs', 'traps', 'cable'),
  ('Cable Wrist Curl', 'forearms', 'cable'),
  ('Calf-Machine Shoulder Shrug', 'traps', 'machine'),
  ('Calf Press', 'calves', 'machine'),
  ('Calf Press On The Leg Press Machine', 'calves', 'machine'),
  ('Calf Raise On A Dumbbell', 'calves', 'dumbbell'),
  ('Calf Raises - With Bands', 'calves', 'bands'),
  ('Calf Stretch Elbows Against Wall', 'calves', null),
  ('Calf Stretch Hands Against Wall', 'calves', null),
  ('Calves-SMR', 'calves', 'foam roll'),
  ('Car Deadlift', 'quadriceps', 'other'),
  ('Car Drivers', 'shoulders', 'barbell'),
  ('Carioca Quick Step', 'adductors', null),
  ('Cat Stretch', 'lower back', null),
  ('Catch and Overhead Throw', 'lats', 'medicine ball'),
  ('Chain Handle Extension', 'triceps', 'other'),
  ('Chain Press', 'chest', 'other'),
  ('Chair Leg Extended Stretch', 'hamstrings', 'other'),
  ('Chair Lower Back Stretch', 'lats', null),
  ('Chair Squat', 'quadriceps', 'machine'),
  ('Chair Upper Body Stretch', 'shoulders', 'other'),
  ('Chest And Front Of Shoulder Stretch', 'chest', 'other'),
  ('Chest Push from 3 point stance', 'chest', 'medicine ball'),
  ('Chest Push (multiple response)', 'chest', 'medicine ball'),
  ('Chest Push (single response)', 'chest', 'medicine ball'),
  ('Chest Push with Run Release', 'chest', 'medicine ball'),
  ('Chest Stretch on Stability Ball', 'chest', 'exercise ball'),
  ('Child''s Pose', 'lower back', null),
  ('Chin-Up', 'lats', 'body only'),
  ('Chin To Chest Stretch', 'neck', null),
  ('Circus Bell', 'shoulders', 'other'),
  ('Clean', 'hamstrings', 'barbell'),
  ('Clean Deadlift', 'hamstrings', 'barbell'),
  ('Clean Pull', 'quadriceps', 'barbell'),
  ('Clean Shrug', 'traps', 'barbell'),
  ('Clean and Jerk', 'shoulders', 'barbell'),
  ('Clean and Press', 'shoulders', 'barbell'),
  ('Clean from Blocks', 'quadriceps', 'barbell'),
  ('Clock Push-Up', 'chest', 'body only'),
  ('Close-Grip Barbell Bench Press', 'triceps', 'barbell'),
  ('Close-Grip Dumbbell Press', 'triceps', 'dumbbell'),
  ('Close-Grip EZ-Bar Curl with Band', 'biceps', 'e-z curl bar'),
  ('Close-Grip EZ-Bar Press', 'triceps', 'e-z curl bar'),
  ('Close-Grip EZ Bar Curl', 'biceps', 'barbell'),
  ('Close-Grip Front Lat Pulldown', 'lats', 'cable'),
  ('Close-Grip Push-Up off of a Dumbbell', 'triceps', 'body only'),
  ('Close-Grip Standing Barbell Curl', 'biceps', 'barbell'),
  ('Cocoons', 'abdominals', 'body only'),
  ('Conan''s Wheel', 'quadriceps', 'other'),
  ('Concentration Curls', 'biceps', 'dumbbell'),
  ('Cross-Body Crunch', 'abdominals', 'body only'),
  ('Cross Body Hammer Curl', 'biceps', 'dumbbell'),
  ('Cross Over - With Bands', 'chest', 'bands'),
  ('Crossover Reverse Lunge', 'lower back', null),
  ('Crucifix', 'shoulders', 'other'),
  ('Crunch - Hands Overhead', 'abdominals', 'body only'),
  ('Crunch - Legs On Exercise Ball', 'abdominals', 'body only'),
  ('Crunches', 'abdominals', 'body only'),
  ('Cuban Press', 'shoulders', 'dumbbell'),
  ('Dancer''s Stretch', 'lower back', null),
  ('Dead Bug', 'abdominals', 'body only'),
  ('Deadlift with Bands', 'lower back', 'barbell'),
  ('Deadlift with Chains', 'lower back', 'barbell'),
  ('Decline Barbell Bench Press', 'chest', 'barbell'),
  ('Decline Close-Grip Bench To Skull Crusher', 'triceps', 'barbell'),
  ('Decline Crunch', 'abdominals', 'body only'),
  ('Decline Dumbbell Bench Press', 'chest', 'dumbbell'),
  ('Decline Dumbbell Flyes', 'chest', 'dumbbell'),
  ('Decline Dumbbell Triceps Extension', 'triceps', 'dumbbell'),
  ('Decline EZ Bar Triceps Extension', 'triceps', 'barbell'),
  ('Decline Oblique Crunch', 'abdominals', 'body only'),
  ('Decline Push-Up', 'chest', null),
  ('Decline Reverse Crunch', 'abdominals', 'body only'),
  ('Decline Smith Press', 'chest', 'machine'),
  ('Deficit Deadlift', 'lower back', 'barbell'),
  ('Depth Jump Leap', 'quadriceps', 'other'),
  ('Dip Machine', 'triceps', 'machine'),
  ('Dips - Chest Version', 'chest', 'other'),
  ('Dips - Triceps Version', 'triceps', 'body only'),
  ('Donkey Calf Raises', 'calves', 'other'),
  ('Double Kettlebell Alternating Hang Clean', 'hamstrings', 'kettlebells'),
  ('Double Kettlebell Jerk', 'shoulders', 'kettlebells'),
  ('Double Kettlebell Push Press', 'shoulders', 'kettlebells'),
  ('Double Kettlebell Snatch', 'shoulders', 'kettlebells'),
  ('Double Kettlebell Windmill', 'abdominals', 'kettlebells'),
  ('Double Leg Butt Kick', 'quadriceps', 'body only'),
  ('Downward Facing Balance', 'glutes', 'exercise ball'),
  ('Drag Curl', 'biceps', 'barbell'),
  ('Drop Push', 'chest', 'other'),
  ('Dumbbell Alternate Bicep Curl', 'biceps', 'dumbbell'),
  ('Dumbbell Bench Press', 'chest', 'dumbbell'),
  ('Dumbbell Bench Press with Neutral Grip', 'chest', 'dumbbell'),
  ('Dumbbell Bicep Curl', 'biceps', 'dumbbell'),
  ('Dumbbell Clean', 'hamstrings', 'dumbbell'),
  ('Dumbbell Floor Press', 'triceps', 'dumbbell'),
  ('Dumbbell Flyes', 'chest', 'dumbbell'),
  ('Dumbbell Incline Row', 'middle back', 'dumbbell'),
  ('Dumbbell Incline Shoulder Raise', 'shoulders', 'dumbbell'),
  ('Dumbbell Lunges', 'quadriceps', 'dumbbell'),
  ('Dumbbell Lying One-Arm Rear Lateral Raise', 'shoulders', 'dumbbell'),
  ('Dumbbell Lying Pronation', 'forearms', 'dumbbell'),
  ('Dumbbell Lying Rear Lateral Raise', 'shoulders', 'dumbbell'),
  ('Dumbbell Lying Supination', 'forearms', 'dumbbell'),
  ('Dumbbell One-Arm Shoulder Press', 'shoulders', 'dumbbell'),
  ('Dumbbell One-Arm Triceps Extension', 'triceps', 'dumbbell'),
  ('Dumbbell One-Arm Upright Row', 'shoulders', 'dumbbell'),
  ('Dumbbell Prone Incline Curl', 'biceps', 'dumbbell'),
  ('Dumbbell Raise', 'shoulders', 'dumbbell'),
  ('Dumbbell Rear Lunge', 'quadriceps', 'dumbbell'),
  ('Dumbbell Scaption', 'shoulders', 'dumbbell'),
  ('Dumbbell Seated Box Jump', 'quadriceps', 'dumbbell'),
  ('Dumbbell Seated One-Leg Calf Raise', 'calves', 'dumbbell'),
  ('Dumbbell Shoulder Press', 'shoulders', 'dumbbell'),
  ('Dumbbell Shrug', 'traps', 'dumbbell'),
  ('Dumbbell Side Bend', 'abdominals', 'dumbbell'),
  ('Dumbbell Squat', 'quadriceps', 'dumbbell'),
  ('Dumbbell Squat To A Bench', 'quadriceps', 'dumbbell'),
  ('Dumbbell Step Ups', 'quadriceps', 'dumbbell'),
  ('Dumbbell Tricep Extension -Pronated Grip', 'triceps', 'dumbbell'),
  ('Dynamic Back Stretch', 'lats', null),
  ('Dynamic Chest Stretch', 'chest', null),
  ('EZ-Bar Curl', 'biceps', 'e-z curl bar'),
  ('EZ-Bar Skullcrusher', 'triceps', 'e-z curl bar'),
  ('Elbow Circles', 'shoulders', null),
  ('Elbow to Knee', 'abdominals', 'body only'),
  ('Elbows Back', 'chest', null),
  ('Elevated Back Lunge', 'quadriceps', 'barbell'),
  ('Elevated Cable Rows', 'lats', 'cable'),
  ('Elliptical Trainer', 'quadriceps', 'machine'),
  ('Exercise Ball Crunch', 'abdominals', 'exercise ball'),
  ('Exercise Ball Pull-In', 'abdominals', 'exercise ball'),
  ('Extended Range One-Arm Kettlebell Floor Press', 'chest', 'kettlebells'),
  ('External Rotation', 'shoulders', 'dumbbell'),
  ('External Rotation with Band', 'shoulders', 'bands'),
  ('External Rotation with Cable', 'shoulders', 'cable'),
  ('Face Pull', 'shoulders', 'cable'),
  ('Farmer''s Walk', 'forearms', 'other'),
  ('Fast Skipping', 'quadriceps', 'body only'),
  ('Finger Curls', 'forearms', 'barbell'),
  ('Flat Bench Cable Flyes', 'chest', 'cable'),
  ('Flat Bench Leg Pull-In', 'abdominals', 'body only'),
  ('Flat Bench Lying Leg Raise', 'abdominals', 'body only'),
  ('Flexor Incline Dumbbell Curls', 'biceps', 'dumbbell'),
  ('Floor Glute-Ham Raise', 'hamstrings', null),
  ('Floor Press', 'triceps', 'barbell'),
  ('Floor Press with Chains', 'triceps', 'barbell'),
  ('Flutter Kicks', 'glutes', 'body only'),
  ('Foot-SMR', 'calves', 'other'),
  ('Forward Drag with Press', 'chest', 'other'),
  ('Frankenstein Squat', 'quadriceps', 'barbell'),
  ('Freehand Jump Squat', 'quadriceps', 'body only'),
  ('Frog Hops', 'quadriceps', null),
  ('Frog Sit-Ups', 'abdominals', 'body only'),
  ('Front Barbell Squat', 'quadriceps', 'barbell'),
  ('Front Barbell Squat To A Bench', 'quadriceps', 'barbell'),
  ('Front Box Jump', 'hamstrings', 'other'),
  ('Front Cable Raise', 'shoulders', 'cable'),
  ('Front Cone Hops (or hurdle hops)', 'quadriceps', 'other'),
  ('Front Dumbbell Raise', 'shoulders', 'dumbbell'),
  ('Front Incline Dumbbell Raise', 'shoulders', 'dumbbell'),
  ('Front Leg Raises', 'hamstrings', 'body only'),
  ('Front Plate Raise', 'shoulders', 'other'),
  ('Front Raise And Pullover', 'chest', 'barbell'),
  ('Front Squat (Clean Grip)', 'quadriceps', 'barbell'),
  ('Front Squats With Two Kettlebells', 'quadriceps', 'kettlebells'),
  ('Front Two-Dumbbell Raise', 'shoulders', 'dumbbell'),
  ('Full Range-Of-Motion Lat Pulldown', 'lats', 'cable'),
  ('Gironda Sternum Chins', 'lats', 'other'),
  ('Glute Ham Raise', 'hamstrings', 'machine'),
  ('Glute Kickback', 'glutes', 'body only'),
  ('Goblet Squat', 'quadriceps', 'kettlebells'),
  ('Good Morning', 'hamstrings', 'barbell'),
  ('Good Morning off Pins', 'hamstrings', 'barbell'),
  ('Gorilla Chin/Crunch', 'abdominals', 'body only'),
  ('Groin and Back Stretch', 'adductors', null),
  ('Groiners', 'adductors', 'body only'),
  ('Hack Squat', 'quadriceps', 'machine'),
  ('Hammer Curls', 'biceps', 'dumbbell'),
  ('Hammer Grip Incline DB Bench Press', 'chest', 'dumbbell'),
  ('Hamstring-SMR', 'hamstrings', 'foam roll'),
  ('Hamstring Stretch', 'hamstrings', null),
  ('Handstand Push-Ups', 'shoulders', 'body only'),
  ('Hang Clean', 'quadriceps', 'barbell'),
  ('Hang Clean - Below the Knees', 'quadriceps', 'barbell'),
  ('Hang Snatch', 'hamstrings', 'barbell'),
  ('Hang Snatch - Below Knees', 'hamstrings', 'barbell'),
  ('Hanging Bar Good Morning', 'hamstrings', 'barbell'),
  ('Hanging Leg Raise', 'abdominals', 'body only'),
  ('Hanging Pike', 'abdominals', 'body only'),
  ('Heaving Snatch Balance', 'quadriceps', 'barbell'),
  ('Heavy Bag Thrust', 'chest', 'other'),
  ('High Cable Curls', 'biceps', 'cable'),
  ('Hip Circles (prone)', 'abductors', 'body only'),
  ('Hip Extension with Bands', 'glutes', 'bands'),
  ('Hip Flexion with Band', 'quadriceps', 'bands'),
  ('Hip Lift with Band', 'glutes', 'bands'),
  ('Hug A Ball', 'lower back', 'exercise ball'),
  ('Hug Knees To Chest', 'lower back', null),
  ('Hurdle Hops', 'hamstrings', 'other'),
  ('Hyperextensions (Back Extensions)', 'lower back', 'other'),
  ('Hyperextensions With No Hyperextension Bench', 'lower back', 'body only'),
  ('IT Band and Glute Stretch', 'abductors', 'other'),
  ('Iliotibial Tract-SMR', 'abductors', 'foam roll'),
  ('Inchworm', 'hamstrings', 'body only'),
  ('Incline Barbell Triceps Extension', 'triceps', 'barbell'),
  ('Incline Bench Pull', 'middle back', 'barbell'),
  ('Incline Cable Chest Press', 'chest', 'cable'),
  ('Incline Cable Flye', 'chest', 'cable'),
  ('Incline Dumbbell Bench With Palms Facing In', 'chest', 'dumbbell'),
  ('Incline Dumbbell Curl', 'biceps', 'dumbbell'),
  ('Incline Dumbbell Flyes', 'chest', 'dumbbell'),
  ('Incline Dumbbell Flyes - With A Twist', 'chest', 'dumbbell'),
  ('Incline Dumbbell Press', 'chest', 'dumbbell'),
  ('Incline Hammer Curls', 'biceps', 'dumbbell'),
  ('Incline Inner Biceps Curl', 'biceps', 'dumbbell'),
  ('Incline Push-Up', 'chest', 'body only'),
  ('Incline Push-Up Close-Grip', 'triceps', 'body only'),
  ('Incline Push-Up Depth Jump', 'chest', 'other'),
  ('Incline Push-Up Medium', 'chest', 'body only'),
  ('Incline Push-Up Reverse Grip', 'chest', 'body only'),
  ('Incline Push-Up Wide', 'chest', 'body only'),
  ('Intermediate Groin Stretch', 'hamstrings', 'other'),
  ('Intermediate Hip Flexor and Quad Stretch', 'quadriceps', 'other'),
  ('Internal Rotation with Band', 'shoulders', 'bands'),
  ('Inverted Row', 'middle back', null),
  ('Inverted Row with Straps', 'middle back', 'other'),
  ('Iron Cross', 'shoulders', 'dumbbell'),
  ('Iron Crosses (stretch)', 'quadriceps', null),
  ('Isometric Chest Squeezes', 'chest', 'body only'),
  ('Isometric Neck Exercise - Front And Back', 'neck', 'body only'),
  ('Isometric Neck Exercise - Sides', 'neck', 'body only'),
  ('Isometric Wipers', 'chest', 'body only'),
  ('JM Press', 'triceps', 'barbell'),
  ('Jackknife Sit-Up', 'abdominals', 'body only'),
  ('Janda Sit-Up', 'abdominals', 'body only'),
  ('Jefferson Squats', 'quadriceps', 'barbell'),
  ('Jerk Balance', 'shoulders', 'barbell'),
  ('Jerk Dip Squat', 'quadriceps', 'barbell'),
  ('Jogging, Treadmill', 'quadriceps', 'machine'),
  ('Keg Load', 'lower back', 'other'),
  ('Kettlebell Arnold Press', 'shoulders', 'kettlebells'),
  ('Kettlebell Dead Clean', 'hamstrings', 'kettlebells'),
  ('Kettlebell Figure 8', 'abdominals', 'kettlebells'),
  ('Kettlebell Halo', 'shoulders', 'kettlebells'),
  ('Kettlebell Halo with Overhead Extension', 'shoulders', 'kettlebells'),
  ('Kettlebell Hang Clean', 'hamstrings', 'kettlebells'),
  ('Kettlebell One-Legged Deadlift', 'hamstrings', 'kettlebells'),
  ('Kettlebell Overhead Triceps Extension', 'triceps', 'kettlebells'),
  ('Kettlebell Pass Between The Legs', 'abdominals', 'kettlebells'),
  ('Kettlebell Pirate Ships', 'shoulders', 'kettlebells'),
  ('Kettlebell Pistol Squat', 'quadriceps', 'kettlebells'),
  ('Kettlebell Seated Press', 'shoulders', 'kettlebells'),
  ('Kettlebell Seesaw Press', 'shoulders', 'kettlebells'),
  ('Kettlebell Sumo High Pull', 'traps', 'kettlebells'),
  ('Kettlebell Thruster', 'shoulders', 'kettlebells'),
  ('Kettlebell Turkish Get-Up (Lunge style)', 'shoulders', 'kettlebells'),
  ('Kettlebell Turkish Get-Up (Squat style)', 'shoulders', 'kettlebells'),
  ('Kettlebell Windmill', 'abdominals', 'kettlebells'),
  ('Kipping Muscle Up', 'lats', 'other'),
  ('Knee Across The Body', 'glutes', null),
  ('Knee Circles', 'calves', 'body only'),
  ('Knee/Hip Raise On Parallel Bars', 'abdominals', 'other'),
  ('Knee Tuck Jump', 'hamstrings', 'body only'),
  ('Kneeling Arm Drill', 'shoulders', null),
  ('Kneeling Cable Crunch With Alternating Oblique Twists', 'abdominals', 'cable'),
  ('Kneeling Cable Triceps Extension', 'triceps', 'cable'),
  ('Kneeling Forearm Stretch', 'forearms', null),
  ('Kneeling High Pulley Row', 'lats', 'cable'),
  ('Kneeling Hip Flexor', 'quadriceps', null),
  ('Kneeling Jump Squat', 'glutes', 'barbell'),
  ('Kneeling Single-Arm High Pulley Row', 'lats', 'cable'),
  ('Kneeling Squat', 'glutes', 'barbell'),
  ('Landmine 180''s', 'abdominals', 'barbell'),
  ('Landmine Linear Jammer', 'shoulders', 'barbell'),
  ('Lateral Bound', 'adductors', 'body only'),
  ('Lateral Box Jump', 'adductors', 'other'),
  ('Lateral Cone Hops', 'adductors', 'other'),
  ('Lateral Raise - With Bands', 'shoulders', 'bands'),
  ('Latissimus Dorsi-SMR', 'lats', 'foam roll'),
  ('Leg-Over Floor Press', 'chest', 'kettlebells'),
  ('Leg-Up Hamstring Stretch', 'hamstrings', null),
  ('Leg Extensions', 'quadriceps', 'machine'),
  ('Leg Lift', 'glutes', 'body only'),
  ('Leg Press', 'quadriceps', 'machine'),
  ('Leg Pull-In', 'abdominals', 'body only'),
  ('Leverage Chest Press', 'chest', 'machine'),
  ('Leverage Deadlift', 'quadriceps', 'machine'),
  ('Leverage Decline Chest Press', 'chest', 'machine'),
  ('Leverage High Row', 'middle back', 'machine'),
  ('Leverage Incline Chest Press', 'chest', 'machine'),
  ('Leverage Iso Row', 'lats', 'machine'),
  ('Leverage Shoulder Press', 'shoulders', 'machine'),
  ('Leverage Shrug', 'traps', 'machine'),
  ('Linear 3-Part Start Technique', 'hamstrings', null),
  ('Linear Acceleration Wall Drill', 'hamstrings', null),
  ('Linear Depth Jump', 'quadriceps', 'other'),
  ('Log Lift', 'shoulders', 'other'),
  ('London Bridges', 'lats', 'other'),
  ('Looking At Ceiling', 'quadriceps', null),
  ('Low Cable Crossover', 'chest', 'cable'),
  ('Low Cable Triceps Extension', 'triceps', 'cable'),
  ('Low Pulley Row To Neck', 'shoulders', 'cable'),
  ('Lower Back-SMR', 'lower back', 'foam roll'),
  ('Lower Back Curl', 'abdominals', 'body only'),
  ('Lunge Pass Through', 'hamstrings', 'kettlebells'),
  ('Lunge Sprint', 'quadriceps', 'machine'),
  ('Lying Bent Leg Groin', 'adductors', 'other'),
  ('Lying Cable Curl', 'biceps', 'cable'),
  ('Lying Cambered Barbell Row', 'middle back', 'barbell'),
  ('Lying Close-Grip Bar Curl On High Pulley', 'biceps', 'cable'),
  ('Lying Close-Grip Barbell Triceps Extension Behind The Head', 'triceps', 'barbell'),
  ('Lying Close-Grip Barbell Triceps Press To Chin', 'triceps', 'e-z curl bar'),
  ('Lying Crossover', 'abductors', 'body only'),
  ('Lying Dumbbell Tricep Extension', 'triceps', 'dumbbell'),
  ('Lying Face Down Plate Neck Resistance', 'neck', 'other'),
  ('Lying Face Up Plate Neck Resistance', 'neck', 'other'),
  ('Lying Glute', 'glutes', 'body only'),
  ('Lying Hamstring', 'hamstrings', 'other'),
  ('Lying High Bench Barbell Curl', 'biceps', 'barbell'),
  ('Lying Leg Curls', 'hamstrings', 'machine'),
  ('Lying Machine Squat', 'quadriceps', 'machine'),
  ('Lying One-Arm Lateral Raise', 'shoulders', 'dumbbell'),
  ('Lying Prone Quadriceps', 'quadriceps', 'body only'),
  ('Lying Rear Delt Raise', 'shoulders', 'dumbbell'),
  ('Lying Supine Dumbbell Curl', 'biceps', 'dumbbell'),
  ('Lying T-Bar Row', 'middle back', 'machine'),
  ('Lying Triceps Press', 'triceps', 'e-z curl bar'),
  ('Machine Bench Press', 'chest', 'machine'),
  ('Machine Bicep Curl', 'biceps', 'machine'),
  ('Machine Preacher Curls', 'biceps', 'machine'),
  ('Machine Shoulder (Military) Press', 'shoulders', 'machine'),
  ('Machine Triceps Extension', 'triceps', 'machine'),
  ('Medicine Ball Chest Pass', 'chest', 'medicine ball'),
  ('Medicine Ball Full Twist', 'abdominals', 'medicine ball'),
  ('Medicine Ball Scoop Throw', 'shoulders', 'medicine ball'),
  ('Middle Back Shrug', 'middle back', 'dumbbell'),
  ('Middle Back Stretch', 'middle back', null),
  ('Mixed Grip Chin', 'middle back', 'other'),
  ('Monster Walk', 'abductors', 'bands'),
  ('Mountain Climbers', 'quadriceps', null),
  ('Moving Claw Series', 'hamstrings', null),
  ('Muscle Snatch', 'hamstrings', 'barbell'),
  ('Muscle Up', 'lats', 'other'),
  ('Narrow Stance Hack Squats', 'quadriceps', 'machine'),
  ('Narrow Stance Leg Press', 'quadriceps', 'machine'),
  ('Narrow Stance Squats', 'quadriceps', 'barbell'),
  ('Natural Glute Ham Raise', 'hamstrings', 'body only'),
  ('Neck-SMR', 'neck', 'other'),
  ('Neck Press', 'chest', 'barbell'),
  ('Oblique Crunches', 'abdominals', 'body only'),
  ('Oblique Crunches - On The Floor', 'abdominals', 'body only'),
  ('Olympic Squat', 'quadriceps', 'barbell'),
  ('On-Your-Back Quad Stretch', 'quadriceps', 'other'),
  ('On Your Side Quad Stretch', 'quadriceps', null),
  ('One-Arm Dumbbell Row', 'middle back', 'dumbbell'),
  ('One-Arm Flat Bench Dumbbell Flye', 'chest', 'dumbbell'),
  ('One-Arm High-Pulley Cable Side Bends', 'abdominals', 'cable'),
  ('One-Arm Incline Lateral Raise', 'shoulders', 'dumbbell'),
  ('One-Arm Kettlebell Clean', 'hamstrings', 'kettlebells'),
  ('One-Arm Kettlebell Clean and Jerk', 'shoulders', 'kettlebells'),
  ('One-Arm Kettlebell Floor Press', 'chest', 'kettlebells'),
  ('One-Arm Kettlebell Jerk', 'shoulders', 'kettlebells'),
  ('One-Arm Kettlebell Military Press To The Side', 'shoulders', 'kettlebells'),
  ('One-Arm Kettlebell Para Press', 'shoulders', 'kettlebells'),
  ('One-Arm Kettlebell Push Press', 'shoulders', 'kettlebells'),
  ('One-Arm Kettlebell Row', 'middle back', 'kettlebells'),
  ('One-Arm Kettlebell Snatch', 'shoulders', 'kettlebells'),
  ('One-Arm Kettlebell Split Jerk', 'shoulders', 'kettlebells'),
  ('One-Arm Kettlebell Split Snatch', 'shoulders', 'kettlebells'),
  ('One-Arm Kettlebell Swings', 'hamstrings', 'kettlebells'),
  ('One-Arm Long Bar Row', 'middle back', 'barbell'),
  ('One-Arm Medicine Ball Slam', 'abdominals', 'medicine ball'),
  ('One-Arm Open Palm Kettlebell Clean', 'hamstrings', 'kettlebells'),
  ('One-Arm Overhead Kettlebell Squats', 'quadriceps', 'kettlebells'),
  ('One-Arm Side Deadlift', 'quadriceps', 'barbell'),
  ('One-Arm Side Laterals', 'shoulders', 'dumbbell'),
  ('One-Legged Cable Kickback', 'glutes', 'cable'),
  ('One Arm Against Wall', 'lats', null),
  ('One Arm Chin-Up', 'middle back', 'other'),
  ('One Arm Dumbbell Bench Press', 'chest', 'dumbbell'),
  ('One Arm Dumbbell Preacher Curl', 'biceps', 'dumbbell'),
  ('One Arm Floor Press', 'triceps', 'barbell'),
  ('One Arm Lat Pulldown', 'lats', 'cable'),
  ('One Arm Pronated Dumbbell Triceps Extension', 'triceps', 'dumbbell'),
  ('One Arm Supinated Dumbbell Triceps Extension', 'triceps', 'dumbbell'),
  ('One Half Locust', 'quadriceps', null),
  ('One Handed Hang', 'lats', 'other'),
  ('One Knee To Chest', 'glutes', null),
  ('One Leg Barbell Squat', 'quadriceps', 'barbell'),
  ('Open Palm Kettlebell Clean', 'hamstrings', 'kettlebells'),
  ('Otis-Up', 'abdominals', 'other'),
  ('Overhead Cable Curl', 'biceps', 'cable'),
  ('Overhead Lat', 'lats', 'other'),
  ('Overhead Slam', 'lats', 'medicine ball'),
  ('Overhead Squat', 'quadriceps', 'barbell'),
  ('Overhead Stretch', 'abdominals', null),
  ('Overhead Triceps', 'triceps', 'body only'),
  ('Pallof Press', 'abdominals', 'cable'),
  ('Pallof Press With Rotation', 'abdominals', 'cable'),
  ('Palms-Down Dumbbell Wrist Curl Over A Bench', 'forearms', 'dumbbell'),
  ('Palms-Down Wrist Curl Over A Bench', 'forearms', 'barbell'),
  ('Palms-Up Barbell Wrist Curl Over A Bench', 'forearms', 'barbell'),
  ('Palms-Up Dumbbell Wrist Curl Over A Bench', 'forearms', 'dumbbell'),
  ('Parallel Bar Dip', 'triceps', 'other'),
  ('Pelvic Tilt Into Bridge', 'lower back', null),
  ('Peroneals-SMR', 'calves', 'foam roll'),
  ('Peroneals Stretch', 'calves', 'other'),
  ('Physioball Hip Bridge', 'glutes', 'exercise ball'),
  ('Pin Presses', 'triceps', 'barbell'),
  ('Piriformis-SMR', 'glutes', 'foam roll'),
  ('Plank', 'abdominals', 'body only'),
  ('Plate Pinch', 'forearms', 'other'),
  ('Plate Twist', 'abdominals', 'other'),
  ('Platform Hamstring Slides', 'hamstrings', 'other'),
  ('Plie Dumbbell Squat', 'quadriceps', 'dumbbell'),
  ('Plyo Kettlebell Pushups', 'chest', 'kettlebells'),
  ('Plyo Push-up', 'chest', 'body only'),
  ('Posterior Tibialis Stretch', 'calves', 'other'),
  ('Power Clean', 'hamstrings', 'barbell'),
  ('Power Clean from Blocks', 'hamstrings', 'barbell'),
  ('Power Jerk', 'quadriceps', 'barbell'),
  ('Power Partials', 'shoulders', 'dumbbell'),
  ('Power Snatch', 'hamstrings', 'barbell'),
  ('Power Snatch from Blocks', 'quadriceps', 'barbell'),
  ('Power Stairs', 'hamstrings', 'other'),
  ('Preacher Curl', 'biceps', 'barbell'),
  ('Preacher Hammer Dumbbell Curl', 'biceps', 'dumbbell'),
  ('Press Sit-Up', 'abdominals', 'barbell'),
  ('Prone Manual Hamstring', 'hamstrings', null),
  ('Prowler Sprint', 'hamstrings', 'other'),
  ('Pull Through', 'glutes', 'cable'),
  ('Pullups', 'lats', 'body only'),
  ('Push-Up Wide', 'chest', 'body only'),
  ('Push-Ups - Close Triceps Position', 'triceps', 'body only'),
  ('Push-Ups With Feet Elevated', 'chest', 'body only'),
  ('Push-Ups With Feet On An Exercise Ball', 'chest', 'exercise ball'),
  ('Push Press', 'shoulders', 'barbell'),
  ('Push Press - Behind the Neck', 'shoulders', 'barbell'),
  ('Push Up to Side Plank', 'chest', 'body only'),
  ('Pushups', 'chest', 'body only'),
  ('Pushups (Close and Wide Hand Positions)', 'chest', 'body only'),
  ('Pyramid', 'lower back', 'exercise ball'),
  ('Quad Stretch', 'quadriceps', 'other'),
  ('Quadriceps-SMR', 'quadriceps', 'foam roll'),
  ('Quick Leap', 'quadriceps', 'other'),
  ('Rack Delivery', 'shoulders', 'barbell'),
  ('Rack Pull with Bands', 'lower back', 'barbell'),
  ('Rack Pulls', 'lower back', 'barbell'),
  ('Rear Leg Raises', 'quadriceps', 'body only'),
  ('Recumbent Bike', 'quadriceps', 'machine'),
  ('Return Push from Stance', 'shoulders', 'medicine ball'),
  ('Reverse Band Bench Press', 'triceps', 'barbell'),
  ('Reverse Band Box Squat', 'quadriceps', 'barbell'),
  ('Reverse Band Deadlift', 'lower back', 'barbell'),
  ('Reverse Band Power Squat', 'quadriceps', 'barbell'),
  ('Reverse Band Sumo Deadlift', 'hamstrings', 'barbell'),
  ('Reverse Barbell Curl', 'biceps', 'barbell'),
  ('Reverse Barbell Preacher Curls', 'biceps', 'e-z curl bar'),
  ('Reverse Cable Curl', 'biceps', 'cable'),
  ('Reverse Crunch', 'abdominals', 'body only'),
  ('Reverse Flyes', 'shoulders', 'dumbbell'),
  ('Reverse Flyes With External Rotation', 'shoulders', 'dumbbell'),
  ('Reverse Grip Bent-Over Rows', 'middle back', 'barbell'),
  ('Reverse Grip Triceps Pushdown', 'triceps', 'cable'),
  ('Reverse Hyperextension', 'hamstrings', 'machine'),
  ('Reverse Machine Flyes', 'shoulders', 'machine'),
  ('Reverse Plate Curls', 'biceps', 'other'),
  ('Reverse Triceps Bench Press', 'triceps', 'barbell'),
  ('Rhomboids-SMR', 'middle back', 'foam roll'),
  ('Rickshaw Carry', 'forearms', 'other'),
  ('Rickshaw Deadlift', 'quadriceps', 'other'),
  ('Ring Dips', 'triceps', 'other'),
  ('Rocket Jump', 'quadriceps', 'body only'),
  ('Rocking Standing Calf Raise', 'calves', 'barbell'),
  ('Rocky Pull-Ups/Pulldowns', 'lats', 'other'),
  ('Romanian Deadlift', 'hamstrings', 'barbell'),
  ('Romanian Deadlift from Deficit', 'hamstrings', 'barbell'),
  ('Rope Climb', 'lats', 'other'),
  ('Rope Crunch', 'abdominals', 'cable'),
  ('Rope Jumping', 'quadriceps', 'other'),
  ('Rope Straight-Arm Pulldown', 'lats', 'cable'),
  ('Round The World Shoulder Stretch', 'shoulders', 'other'),
  ('Rowing, Stationary', 'quadriceps', 'machine'),
  ('Runner''s Stretch', 'hamstrings', null),
  ('Running, Treadmill', 'quadriceps', 'machine'),
  ('Russian Twist', 'abdominals', 'body only'),
  ('Sandbag Load', 'quadriceps', 'other'),
  ('Scapular Pull-Up', 'traps', null),
  ('Scissor Kick', 'abdominals', 'body only'),
  ('Scissors Jump', 'quadriceps', 'body only'),
  ('Seated Band Hamstring Curl', 'hamstrings', 'other'),
  ('Seated Barbell Military Press', 'shoulders', 'barbell'),
  ('Seated Barbell Twist', 'abdominals', 'barbell'),
  ('Seated Bent-Over One-Arm Dumbbell Triceps Extension', 'triceps', 'dumbbell'),
  ('Seated Bent-Over Rear Delt Raise', 'shoulders', 'dumbbell'),
  ('Seated Bent-Over Two-Arm Dumbbell Triceps Extension', 'triceps', 'dumbbell'),
  ('Seated Biceps', 'biceps', 'body only'),
  ('Seated Cable Rows', 'middle back', 'cable'),
  ('Seated Cable Shoulder Press', 'shoulders', 'cable'),
  ('Seated Calf Raise', 'calves', 'machine'),
  ('Seated Calf Stretch', 'calves', null),
  ('Seated Close-Grip Concentration Barbell Curl', 'biceps', 'barbell'),
  ('Seated Dumbbell Curl', 'biceps', 'dumbbell'),
  ('Seated Dumbbell Inner Biceps Curl', 'biceps', 'dumbbell'),
  ('Seated Dumbbell Palms-Down Wrist Curl', 'forearms', 'dumbbell'),
  ('Seated Dumbbell Palms-Up Wrist Curl', 'forearms', 'dumbbell'),
  ('Seated Dumbbell Press', 'shoulders', 'dumbbell'),
  ('Seated Flat Bench Leg Pull-In', 'abdominals', 'body only'),
  ('Seated Floor Hamstring Stretch', 'hamstrings', null),
  ('Seated Front Deltoid', 'shoulders', 'body only'),
  ('Seated Glute', 'glutes', 'body only'),
  ('Seated Good Mornings', 'lower back', 'barbell'),
  ('Seated Hamstring', 'hamstrings', null),
  ('Seated Hamstring and Calf Stretch', 'hamstrings', 'other'),
  ('Seated Head Harness Neck Resistance', 'neck', 'other'),
  ('Seated Leg Curl', 'hamstrings', 'machine'),
  ('Seated Leg Tucks', 'abdominals', 'body only'),
  ('Seated One-Arm Dumbbell Palms-Down Wrist Curl', 'forearms', 'dumbbell'),
  ('Seated One-Arm Dumbbell Palms-Up Wrist Curl', 'forearms', 'dumbbell'),
  ('Seated One-arm Cable Pulley Rows', 'middle back', 'cable'),
  ('Seated Overhead Stretch', 'abdominals', null),
  ('Seated Palm-Up Barbell Wrist Curl', 'forearms', 'barbell'),
  ('Seated Palms-Down Barbell Wrist Curl', 'forearms', 'barbell'),
  ('Seated Side Lateral Raise', 'shoulders', 'dumbbell'),
  ('Seated Triceps Press', 'triceps', 'dumbbell'),
  ('Seated Two-Arm Palms-Up Low-Pulley Wrist Curl', 'forearms', 'cable'),
  ('See-Saw Press (Alternating Side Press)', 'shoulders', 'dumbbell'),
  ('Shotgun Row', 'lats', 'cable'),
  ('Shoulder Circles', 'shoulders', null),
  ('Shoulder Press - With Bands', 'shoulders', 'bands'),
  ('Shoulder Raise', 'shoulders', null),
  ('Shoulder Stretch', 'shoulders', null),
  ('Side-Lying Floor Stretch', 'lats', null),
  ('Side Bridge', 'abdominals', 'body only'),
  ('Side Hop-Sprint', 'quadriceps', 'other'),
  ('Side Jackknife', 'abdominals', 'body only'),
  ('Side Lateral Raise', 'shoulders', 'dumbbell'),
  ('Side Laterals to Front Raise', 'shoulders', 'dumbbell'),
  ('Side Leg Raises', 'adductors', 'body only'),
  ('Side Lying Groin Stretch', 'adductors', null),
  ('Side Neck Stretch', 'neck', null),
  ('Side Standing Long Jump', 'quadriceps', null),
  ('Side To Side Chins', 'lats', 'other'),
  ('Side Wrist Pull', 'shoulders', null),
  ('Side to Side Box Shuffle', 'quadriceps', 'other'),
  ('Single-Arm Cable Crossover', 'chest', 'cable'),
  ('Single-Arm Linear Jammer', 'shoulders', 'barbell'),
  ('Single-Arm Push-Up', 'chest', 'body only'),
  ('Single-Cone Sprint Drill', 'quadriceps', 'other'),
  ('Single-Leg High Box Squat', 'quadriceps', 'other'),
  ('Single-Leg Hop Progression', 'quadriceps', 'other'),
  ('Single-Leg Lateral Hop', 'quadriceps', 'other'),
  ('Single-Leg Leg Extension', 'quadriceps', 'machine'),
  ('Single-Leg Stride Jump', 'quadriceps', 'other'),
  ('Single Dumbbell Raise', 'shoulders', 'dumbbell'),
  ('Single Leg Butt Kick', 'quadriceps', 'body only'),
  ('Single Leg Glute Bridge', 'glutes', 'body only'),
  ('Single Leg Push-off', 'quadriceps', 'other'),
  ('Sit-Up', 'abdominals', 'body only'),
  ('Sit Squats', 'quadriceps', null),
  ('Skating', 'quadriceps', 'other'),
  ('Sled Drag - Harness', 'quadriceps', 'other'),
  ('Sled Overhead Backward Walk', 'shoulders', 'other'),
  ('Sled Overhead Triceps Extension', 'triceps', 'other'),
  ('Sled Push', 'quadriceps', 'other'),
  ('Sled Reverse Flye', 'shoulders', 'other'),
  ('Sled Row', 'middle back', 'other'),
  ('Sledgehammer Swings', 'abdominals', 'other'),
  ('Smith Incline Shoulder Raise', 'shoulders', 'barbell'),
  ('Smith Machine Behind the Back Shrug', 'traps', 'machine'),
  ('Smith Machine Bench Press', 'chest', 'machine'),
  ('Smith Machine Bent Over Row', 'middle back', 'machine'),
  ('Smith Machine Calf Raise', 'calves', 'machine'),
  ('Smith Machine Close-Grip Bench Press', 'triceps', 'machine'),
  ('Smith Machine Decline Press', 'chest', 'machine'),
  ('Smith Machine Hang Power Clean', 'hamstrings', 'machine'),
  ('Smith Machine Hip Raise', 'abdominals', 'machine'),
  ('Smith Machine Incline Bench Press', 'chest', 'machine'),
  ('Smith Machine Leg Press', 'quadriceps', 'machine'),
  ('Smith Machine One-Arm Upright Row', 'shoulders', 'machine'),
  ('Smith Machine Overhead Shoulder Press', 'shoulders', 'machine'),
  ('Smith Machine Pistol Squat', 'quadriceps', 'machine'),
  ('Smith Machine Reverse Calf Raises', 'calves', 'machine'),
  ('Smith Machine Squat', 'quadriceps', 'machine'),
  ('Smith Machine Stiff-Legged Deadlift', 'hamstrings', 'machine'),
  ('Smith Machine Upright Row', 'traps', 'machine'),
  ('Smith Single-Leg Split Squat', 'quadriceps', 'machine'),
  ('Snatch', 'quadriceps', 'barbell'),
  ('Snatch Balance', 'quadriceps', 'barbell'),
  ('Snatch Deadlift', 'hamstrings', 'barbell'),
  ('Snatch Pull', 'hamstrings', 'barbell'),
  ('Snatch Shrug', 'traps', 'barbell'),
  ('Snatch from Blocks', 'quadriceps', 'barbell'),
  ('Speed Band Overhead Triceps', 'triceps', 'bands'),
  ('Speed Box Squat', 'quadriceps', 'barbell'),
  ('Speed Squats', 'quadriceps', 'barbell'),
  ('Spell Caster', 'abdominals', 'dumbbell'),
  ('Spider Crawl', 'abdominals', 'body only'),
  ('Spider Curl', 'biceps', 'e-z curl bar'),
  ('Spinal Stretch', 'middle back', null),
  ('Split Clean', 'quadriceps', 'barbell'),
  ('Split Jerk', 'quadriceps', 'barbell'),
  ('Split Jump', 'quadriceps', 'body only'),
  ('Split Snatch', 'hamstrings', 'barbell'),
  ('Split Squat with Dumbbells', 'quadriceps', 'dumbbell'),
  ('Split Squats', 'hamstrings', null),
  ('Squat Jerk', 'quadriceps', 'barbell'),
  ('Squat with Bands', 'quadriceps', 'barbell'),
  ('Squat with Chains', 'quadriceps', 'barbell'),
  ('Squat with Plate Movers', 'quadriceps', 'barbell'),
  ('Squats - With Bands', 'quadriceps', 'bands'),
  ('Stairmaster', 'quadriceps', 'machine'),
  ('Standing Alternating Dumbbell Press', 'shoulders', 'dumbbell'),
  ('Standing Barbell Calf Raise', 'calves', 'barbell'),
  ('Standing Barbell Press Behind Neck', 'shoulders', 'barbell'),
  ('Standing Bent-Over One-Arm Dumbbell Triceps Extension', 'triceps', 'dumbbell'),
  ('Standing Bent-Over Two-Arm Dumbbell Triceps Extension', 'triceps', 'dumbbell'),
  ('Standing Biceps Cable Curl', 'biceps', 'cable'),
  ('Standing Biceps Stretch', 'biceps', 'other'),
  ('Standing Bradford Press', 'shoulders', 'barbell'),
  ('Standing Cable Chest Press', 'chest', 'cable'),
  ('Standing Cable Lift', 'abdominals', 'cable'),
  ('Standing Cable Wood Chop', 'abdominals', 'cable'),
  ('Standing Calf Raises', 'calves', 'machine'),
  ('Standing Concentration Curl', 'biceps', 'dumbbell'),
  ('Standing Dumbbell Calf Raise', 'calves', 'dumbbell'),
  ('Standing Dumbbell Press', 'shoulders', 'dumbbell'),
  ('Standing Dumbbell Reverse Curl', 'biceps', 'dumbbell'),
  ('Standing Dumbbell Straight-Arm Front Delt Raise Above Head', 'shoulders', 'dumbbell'),
  ('Standing Dumbbell Triceps Extension', 'triceps', 'dumbbell'),
  ('Standing Dumbbell Upright Row', 'traps', 'dumbbell'),
  ('Standing Elevated Quad Stretch', 'quadriceps', 'other'),
  ('Standing Front Barbell Raise Over Head', 'shoulders', 'barbell'),
  ('Standing Gastrocnemius Calf Stretch', 'calves', null),
  ('Standing Hamstring and Calf Stretch', 'hamstrings', 'other'),
  ('Standing Hip Circles', 'abductors', 'body only'),
  ('Standing Hip Flexors', 'quadriceps', null),
  ('Standing Inner-Biceps Curl', 'biceps', 'dumbbell'),
  ('Standing Lateral Stretch', 'abdominals', null),
  ('Standing Leg Curl', 'hamstrings', 'machine'),
  ('Standing Long Jump', 'quadriceps', 'body only'),
  ('Standing Low-Pulley Deltoid Raise', 'shoulders', 'cable'),
  ('Standing Low-Pulley One-Arm Triceps Extension', 'triceps', 'cable'),
  ('Standing Military Press', 'shoulders', 'barbell'),
  ('Standing Olympic Plate Hand Squeeze', 'forearms', 'other'),
  ('Standing One-Arm Cable Curl', 'biceps', 'cable'),
  ('Standing One-Arm Dumbbell Curl Over Incline Bench', 'biceps', 'dumbbell'),
  ('Standing One-Arm Dumbbell Triceps Extension', 'triceps', 'dumbbell'),
  ('Standing Overhead Barbell Triceps Extension', 'triceps', 'barbell'),
  ('Standing Palm-In One-Arm Dumbbell Press', 'shoulders', 'dumbbell'),
  ('Standing Palms-In Dumbbell Press', 'shoulders', 'dumbbell'),
  ('Standing Palms-Up Barbell Behind The Back Wrist Curl', 'forearms', 'barbell'),
  ('Standing Pelvic Tilt', 'lower back', null),
  ('Standing Rope Crunch', 'abdominals', 'cable'),
  ('Standing Soleus And Achilles Stretch', 'calves', null),
  ('Standing Toe Touches', 'hamstrings', null),
  ('Standing Towel Triceps Extension', 'triceps', 'body only'),
  ('Standing Two-Arm Overhead Throw', 'shoulders', 'medicine ball'),
  ('Star Jump', 'quadriceps', 'body only'),
  ('Step-up with Knee Raise', 'glutes', 'body only'),
  ('Step Mill', 'quadriceps', 'machine'),
  ('Stiff-Legged Barbell Deadlift', 'hamstrings', 'barbell'),
  ('Stiff-Legged Dumbbell Deadlift', 'hamstrings', 'dumbbell'),
  ('Stiff Leg Barbell Good Morning', 'lower back', 'barbell'),
  ('Stomach Vacuum', 'abdominals', 'body only'),
  ('Straight-Arm Dumbbell Pullover', 'chest', 'dumbbell'),
  ('Straight-Arm Pulldown', 'lats', 'cable'),
  ('Straight Bar Bench Mid Rows', 'middle back', 'barbell'),
  ('Straight Raises on Incline Bench', 'shoulders', 'barbell'),
  ('Stride Jump Crossover', 'quadriceps', 'other'),
  ('Sumo Deadlift', 'hamstrings', 'barbell'),
  ('Sumo Deadlift with Bands', 'hamstrings', 'barbell'),
  ('Sumo Deadlift with Chains', 'hamstrings', 'barbell'),
  ('Superman', 'lower back', 'body only'),
  ('Supine Chest Throw', 'triceps', 'medicine ball'),
  ('Supine One-Arm Overhead Throw', 'abdominals', 'medicine ball'),
  ('Supine Two-Arm Overhead Throw', 'abdominals', 'medicine ball'),
  ('Suspended Fallout', 'abdominals', 'other'),
  ('Suspended Push-Up', 'chest', 'other'),
  ('Suspended Reverse Crunch', 'abdominals', 'other'),
  ('Suspended Row', 'middle back', 'other'),
  ('Suspended Split Squat', 'quadriceps', 'other'),
  ('Svend Press', 'chest', 'other'),
  ('T-Bar Row with Handle', 'middle back', 'barbell'),
  ('Tate Press', 'triceps', 'dumbbell'),
  ('The Straddle', 'hamstrings', null),
  ('Thigh Abductor', 'abductors', 'machine'),
  ('Thigh Adductor', 'adductors', 'machine'),
  ('Tire Flip', 'quadriceps', 'other'),
  ('Toe Touchers', 'abdominals', 'body only'),
  ('Torso Rotation', 'abdominals', 'exercise ball'),
  ('Trail Running/Walking', 'quadriceps', null),
  ('Trap Bar Deadlift', 'quadriceps', 'other'),
  ('Tricep Dumbbell Kickback', 'triceps', 'dumbbell'),
  ('Tricep Side Stretch', 'triceps', null),
  ('Triceps Overhead Extension with Rope', 'triceps', 'cable'),
  ('Triceps Pushdown', 'triceps', 'cable'),
  ('Triceps Pushdown - Rope Attachment', 'triceps', 'cable'),
  ('Triceps Pushdown - V-Bar Attachment', 'triceps', 'cable'),
  ('Triceps Stretch', 'triceps', null),
  ('Tuck Crunch', 'abdominals', 'body only'),
  ('Two-Arm Dumbbell Preacher Curl', 'biceps', 'dumbbell'),
  ('Two-Arm Kettlebell Clean', 'shoulders', 'kettlebells'),
  ('Two-Arm Kettlebell Jerk', 'shoulders', 'kettlebells'),
  ('Two-Arm Kettlebell Military Press', 'shoulders', 'kettlebells'),
  ('Two-Arm Kettlebell Row', 'middle back', 'kettlebells'),
  ('Underhand Cable Pulldowns', 'lats', 'cable'),
  ('Upper Back-Leg Grab', 'hamstrings', null),
  ('Upper Back Stretch', 'middle back', null),
  ('Upright Barbell Row', 'shoulders', 'barbell'),
  ('Upright Cable Row', 'traps', 'cable'),
  ('Upright Row - With Bands', 'traps', 'bands'),
  ('Upward Stretch', 'shoulders', null),
  ('V-Bar Pulldown', 'lats', 'cable'),
  ('V-Bar Pullup', 'lats', 'body only'),
  ('Vertical Swing', 'hamstrings', 'dumbbell'),
  ('Walking, Treadmill', 'quadriceps', 'machine'),
  ('Weighted Ball Hyperextension', 'lower back', 'exercise ball'),
  ('Weighted Ball Side Bend', 'abdominals', 'exercise ball'),
  ('Weighted Bench Dip', 'triceps', 'other'),
  ('Weighted Crunches', 'abdominals', 'medicine ball'),
  ('Weighted Jump Squat', 'quadriceps', 'barbell'),
  ('Weighted Pull Ups', 'lats', 'other'),
  ('Weighted Sissy Squat', 'quadriceps', 'barbell'),
  ('Weighted Sit-Ups - With Bands', 'abdominals', 'other'),
  ('Weighted Squat', 'quadriceps', 'other'),
  ('Wide-Grip Barbell Bench Press', 'chest', 'barbell'),
  ('Wide-Grip Decline Barbell Bench Press', 'chest', 'barbell'),
  ('Wide-Grip Decline Barbell Pullover', 'chest', 'barbell'),
  ('Wide-Grip Lat Pulldown', 'lats', 'cable'),
  ('Wide-Grip Pulldown Behind The Neck', 'lats', 'cable'),
  ('Wide-Grip Rear Pull-Up', 'lats', 'body only'),
  ('Wide-Grip Standing Barbell Curl', 'biceps', 'barbell'),
  ('Wide Stance Barbell Squat', 'quadriceps', 'barbell'),
  ('Wide Stance Stiff Legs', 'hamstrings', 'barbell'),
  ('Wind Sprints', 'abdominals', 'body only'),
  ('Windmills', 'abductors', null),
  ('World''s Greatest Stretch', 'hamstrings', null),
  ('Wrist Circles', 'forearms', 'body only'),
  ('Wrist Roller', 'forearms', 'other'),
  ('Wrist Rotations with Straight Bar', 'forearms', 'barbell'),
  ('Yoke Walk', 'quadriceps', 'other'),
  ('Zercher Squats', 'quadriceps', 'barbell'),
  ('Zottman Curl', 'biceps', 'dumbbell'),
  ('Zottman Preacher Curl', 'biceps', 'dumbbell');
